### ISSUE TITLE
bug (master)!: fails github 3 checks

### ISSUE THREAD

**Issue by NGXZS** [AY2324S2-CS2113-F15-1/tp#26]

**Comment by songyuew** [comment]
My bug is fixed, which was due to a naming issue (better to set a utility class to `final`). I can see there is still some bugs on @hongyijie06 side.

In the `Parser.java` of your latest PR, I can see you called a `processStartCommand()` function in the `parseCommand` function. However, the `processStartCommand` is not implemented in your code. 
![image](https://github.com/AY2324S2-CS2113-F15-1/tp/assets/98693645/d5dbffed-2b64-4111-adc7-0b8e146a745a)

Please kindly check.

**Comment by cyhjason29** [comment]
Bugs have been resolved, checks pass now
